package:
  name: landmarkerio
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0  # [py2k]
    - menpo 0.7.*
    - menpo3d 0.4.*
    - flask 0.10.1
    - flask-restful 0.2.12
    - cherrypy 3.8.0
    - joblib 0.8.4
    - pyyaml 3.11

test:
  imports:
    - landmarkerio

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
